[package]
name = "fractal-shaders"
version = "0.1.0"
authors = ["Christoph Senn <chrigi.senn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"